AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
      cucuyo service app

Globals:
    Function:
        Timeout: 20

    Api:
        Cors:
            AllowMethods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
            AllowHeaders: "'Content-Type, Authorization, X-Amz-Date, X-Api-Key, X-Amz-Security-Token'"
            AllowOrigin: "'*'"
            MaxAge: "'600'"

Resources:
    PropertiesFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: target/cucuyo-service-0.0.1-SNAPSHOT.jar
            Handler: com.cucuyo.aws.CreatePropertiesHandler::handleRequest
            Runtime: java8
            Events:
                PropertiesApi:
                    Type: Api
                    Properties:
                        Path: /properties
                        Method: POST
    OptionsFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: target/cucuyo-service-0.0.1-SNAPSHOT.jar
            Handler: com.cucuyo.aws.OptionsHandler::handleRequest
            Runtime: java8
            Events:
                PropertiesApi:
                    Type: Api
                    Properties:
                        Path: /properties
                        Method: OPTIONS


Outputs:

    PropertiesApi:
      Description: "API Gateway endpoint URL for  stage for properties endpoint"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"