AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
      cucuyo service app

Globals:
    Function:
        Timeout: 20

Resources:

    PropertiesFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: target/cucuyo-service-0.0.1-SNAPSHOT.jar
            Handler: com.cucuyo.aws.PropertiesHandler::handleRequest
            Runtime: java8
            Events:
                PropertiesApi:
                    Type: Api
                    Properties:
                        Path: /properties
                        Method: ANY

    UsersFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: target/cucuyo-service-0.0.1-SNAPSHOT.jar
            Handler: com.cucuyo.aws.UserHandler::handleRequest
            Runtime: java8
            Events:
                UsersApi:
                    Type: Api
                    Properties:
                        Path: /users
                        Method: ANY
                UsersLoginApi:
                    Type: Api
                    Properties:
                        Path: /login
                        Method: ANY



Outputs:

    PropertiesApi:
      Description: "API Gateway endpoint URL for  stage for properties endpoint"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"