AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
      cucuyo service app

Globals:
    Function:
        Timeout: 20

Resources:

    PropertiesGetFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: target/cucuyo-service-0.0.1-SNAPSHOT.jar
            Handler: com.cucuyo.aws.GetPropertiesHandler::handleRequest
            Runtime: java8
            Events:
                PropertiesApi:
                    Type: Api
                    Properties:
                        Path: /properties
                        Method: GET

    PropertiesPostFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: target/cucuyo-service-0.0.1-SNAPSHOT.jar
            Handler: com.cucuyo.aws.CreatePropertiesHandler::handleRequest
            Runtime: java8
            Events:
                PropertiesApi:
                    Type: Api
                    Properties:
                        Path: /properties
                        Method: POST

    OptionsFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: target/cucuyo-service-0.0.1-SNAPSHOT.jar
            Handler: com.cucuyo.aws.OptionsHandler::handleRequest
            Runtime: java8
            Events:
                PropertiesApi:
                    Type: Api
                    Properties:
                        Path: /properties
                        Method: OPTIONS


Outputs:

    PropertiesApi:
      Description: "API Gateway endpoint URL for  stage for properties endpoint"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"