server:
  port: 9000
spring:
  data:
    cassandra:
      keyspace-name: cucuyo
cassandra:
  migration:
    keyspace-name: ${spring.data.cassandra.keyspace-name}
cucuyo:
  setup:
    import-enabled: true
